[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10
rootDirectory = "backend"
