[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = { default = "8000" }
PYTHON_VERSION = { default = "3.11" }